apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: nodejs-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nodejs-app
  policy:
    semver:
      range: "0.x"
