apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: nodejs-image-update
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: nodejs-app
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: ozdemir.fatmanur18@gmail.com
        name: fatmanurozdemir
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: master
  update:
    path: ./clusters/my-cluster
    strategy: Setters
