apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nodejs-express-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nodejs-express-mysql
    namespace: flux-system
  policy:
    numerical:
      order: asc

