apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nodejs-app
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helmchart/nodejs-express-mysql/
      sourceRef:
        kind: GitRepository
        name: nodejs-app
  values:
    image:
      repository: fatmanurdocker/nodejs-express-mysql
      tag: "0.1" # it will be set by Flux based on the ImagePolicy
      pullPolicy: Always

