apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: nodejs-image-update
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: nodejs-app
  git:
    commit:
      author:
        email: ozdemir.fatmanur18@gmail.com
        name: fatmanurozdemir
    push:
      branch: master
  update:
    path: ./
