apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nodejs-express-mysql
  namespace: flux-system
spec:
  interval: 1m  # Reconcile the release every 1 minute
  releaseName: nodejs-express-mysql
  chart:
    spec:
      chart: ./helmchart/nodejs-express-mysql  # Path to your Helm chart
      sourceRef:
        kind: GitRepository
        name: nodejs-app
        namespace: flux-system
  values:
    image:
      repository: fatmanurdocker/nodejs-express-mysql
      tag: "{{ .Values.policy.nodejs-app-policy.latest }}"

