apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nodejs-express-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nodejs-express-app
    namespace: flux-system
  policy:
    semver:
      range: '>=0.1.0'

