apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nodejs-app
spec:
  interval: 1m
  url: https://github.com/fatmanurozdemir/nodejs-express-mysql.git
  ref:
    branch: master

